######################################################################
# Automatically generated by qmake (3.0) Mon Oct 26 22:32:34 2015
######################################################################

TEMPLATE = app
TARGET = ttyline2tcp
INCLUDEPATH += .

QT = core serialport network


# Input
SOURCES += main.cpp
